# Generated by Django 4.0.1 on 2022-02-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Интересные страны', 'verbose_name_plural': 'Интересные страны'},
        ),
        migrations.AlterField(
            model_name='country',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='country.continent', verbose_name='Континент'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название страны'),
        ),
    ]
