# Generated by Django 4.0.1 on 2022-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_options_alter_country_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Интересные страны', 'verbose_name_plural': 'Интересные страны'},
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
