# Generated by Django 4.0.1 on 2022-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_continent_name_alter_country_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Континент', 'verbose_name_plural': 'Континенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Интересные страны', 'verbose_name_plural': 'Интересные страны'},
        ),
    ]
