# Generated by Django 4.0.1 on 2022-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_options_country_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.FloatField(blank=True, null=True, verbose_name='Популяция'),
        ),
    ]
